#!/usr/bin/env bash

notebook=$1
case $notebook in
     *.ipynb) notebook=${notebook::-6};;
     *) notebook=$notebook;;
esac

jupyter nbconvert \
        --to notebook \
        --execute --debug --allow-errors --ExecutePreprocessor.timeout=None \
        --output "$notebook.$(date +%Y-%m-%dT%H-%M-%S).ipynb" \
        "$notebook" \
    | tee "$notebook.$(date +%Y-%m-%dT%H-%M-%S).debug-output"
